source 'https://github.com/CocoaPods/Specs.git'

# 对于Swift应用来说下面两句是必须的
platform :ios, '8.0'
use_frameworks!

target 'SwiftGitTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire','>=4.0'
  # Pods for New2Swift4
    pod 'MJRefresh',                '~> 3.1.12'

  # 'node_modules'目录一般位于根目录中
  # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
    'RCTText',
    'RCTImage',
    'RCTActionSheet',
    'RCTNetwork',
    'ART',
    'RCTLinkingIOS',
    'RCTAnimation',
    'RCTCameraRoll',
    'RCTWebSocket', # 这个模块是用于调试功能的
    # 在这里继续添加你所需要的模块
  ]
  # 如果你的RN版本 >= 0.42.0，请加入下面这行
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"


  target 'SwiftGitTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftGitTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
